
flib_version=0.1.1
flib_file=8006351

mod_id=veincreeper
curse_slug=vein-creeper
curse_id=907093
mod_version=1.2.1
mod_group_id=com.lothrazar.veincreeper
mod_license=SeeGithub
mod_authors=Lothrazar
mod_name=veincreeper
mod_description=veincreeper

modrinth_id=vein-creeper
